version: '3'
services:
  redis-server:
    container_name: redis-server
    image: 'redis:latest'
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  backend:
    container_name: lottery_backend
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"